name: Build and Publish image to Docker
on: 
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./api/ -t mnick28/devops-qr-code-ap:latest
      - name: push image to docker hub
        run: |
          docker push mnick28/devops-qr-code-ap:latest